$(PACKAGE_DIR)/data/01-sample.in : $(SOURCE_DIR)/data/01-sample.txt $(BUILD_DIR)/validator
	@mkdir -p $(dir $@)
	@echo + [CP] $@
	@$(CP) $< $@
	@echo + [VALIDATE] $@
	@$(BUILD_DIR)/validator < $@

$(PACKAGE_DIR)/data/02-sample.in : $(SOURCE_DIR)/data/02-sample.txt $(BUILD_DIR)/validator
	@mkdir -p $(dir $@)
	@echo + [CP] $@
	@$(CP) $< $@
	@echo + [VALIDATE] $@
	@$(BUILD_DIR)/validator < $@

$(PACKAGE_DIR)/data/03-random.in : $(BUILD_DIR)/data/rand1 $(BUILD_DIR)/validator
	@mkdir -p $(dir $@)
	@echo + [GEN] $@
	@$(BUILD_DIR)/data/rand1 51795452 10 < $< > $@
	@echo + [VALIDATE] $@
	@$(BUILD_DIR)/validator < $@

$(PACKAGE_DIR)/data/04-random.in : $(BUILD_DIR)/data/rand1 $(BUILD_DIR)/validator
	@mkdir -p $(dir $@)
	@echo + [GEN] $@
	@$(BUILD_DIR)/data/rand1 51795453 10 < $< > $@
	@echo + [VALIDATE] $@
	@$(BUILD_DIR)/validator < $@

DATA_TARGETS = \
  $(PACKAGE_DIR)/data/01-sample.ans \
  $(PACKAGE_DIR)/data/02-sample.ans \
  $(PACKAGE_DIR)/data/03-random.ans \
  $(PACKAGE_DIR)/data/04-random.ans
